#!/usr/bin/env bash

set -e

cd "$GOPATH" || exit
if $RACE; then
    echo "$ go build -race -o bin/main main.go"
    go build -race -o bin/main main.go
else
    echo "$ go build -o bin/main main.go"
    go build -o bin/main main.go
fi
bin/main
